alias cp='cp -iv'
alias h='history 50'
#alias hexd='od -t x1 -A x -v'
alias hexd='hexdump -C'
alias la='ls -alGh'
alias ll='ls -lGh'
alias mv='mv -iv'
alias rm='rm -i'

alias tailm='tail -40 /var/log/messages'

if [ -f ~/.illumicone_aliases ]; then
    . ~/.illumicone_aliases
fi
