#! /bin/bash

# icpf:  push/pull a file to/from a remote Illumicone host via a jump server.

if [ $# -lt 4 ]; then
    echo "Usage:  $0 push|pull hostname source... dest"
    exit 2
fi

if [ -z $ILLUMICONE_JUMPER ]; then
    echo "ILLUMICONE_JUMPER is not defined in the environment."
    exit 1
fi

pushpull=$1
shift
hostname=$1
shift
sources=()
while [[ $# -gt 1 ]]; do
    sources+=($1)
    shift
done
dest=$1

if [ "$pushpull" != "push" -a "$pushpull" != "pull" ]; then
    echo "Specify push or pull."
    exit 1
fi

hostinfo=`ssh $ILLUMICONE_JUMPER "grep -A 6 \"$hostname\$\" ~/.ssh/config | egrep '(Port|User)[[:space:]]+[[:alnum:]]+' | awk '{print \\$1,\\$2}' | tr '\n' ' '"`
port=`echo "$hostinfo" | sed -En -e 's/.*Port ([[:digit:]]+).*/\1/p'`
user=`echo "$hostinfo" | sed -En -e 's/.*User ([[:alnum:]]+).*/\1/p'`

if [ -z $port ] || [ -z $user ]; then
    echo "$hostname is not in ~/.ssh/config at $ILLUMICONE_JUMPER, or Port and/or User are not specified for it."
    exit 1
fi

if [ "$pushpull" == "push" ]; then
    echo "Copying to $hostname via tunneling port $port at $ILLUMICONE_JUMPER..."
    scp -o "ProxyJump $ILLUMICONE_JUMPER" -P $port ${sources[*]} $user@127.0.0.1:$dest
else
    echo "Copying from $hostname via tunneling port $port at $ILLUMICONE_JUMPER..."
    scp -o "ProxyJump $ILLUMICONE_JUMPER" -P $port $user@127.0.0.1:${sources[*]} $dest
fi

