#! /bin/bash

# icpf:  push/pull a file to/from a remote Illumicone host via a jump server.

#set -x

if [ $# -lt 4 ]; then
    echo << EOT "
Usage:  $0 push|pull hostname source... dest

Quote filenames containing spaces or other crap characters
rather than escaping the crap characters.
"
EOT
    exit 2
fi

if [ -z $ILLUMICONE_JUMPER ]; then
    echo "ILLUMICONE_JUMPER is not defined in the environment."
    exit 1
fi

pushpull=$1
shift
hostname=$1
shift
##sources=()
sourcestr=""
while [[ $# -gt 1 ]]; do
    #echo "1=+$1+"
    sourcestr+="'$1' "
    shift
done
#echo "sourcestr=+$sourcestr+"
dest=$1

if [ "$pushpull" != "push" -a "$pushpull" != "pull" ]; then
    echo "Specify push or pull."
    exit 1
fi

hostinfo=`ssh $ILLUMICONE_JUMPER "grep -A 6 \"$hostname\$\" ~/.ssh/config | egrep '(Port|User)[[:space:]]+[[:alnum:]]+' | awk '{print \\$1,\\$2}' | tr '\n' ' '"`
port=`echo "$hostinfo" | sed -En -e 's/.*Port ([[:digit:]]+).*/\1/p'`
user=`echo "$hostinfo" | sed -En -e 's/.*User ([[:alnum:]]+).*/\1/p'`

if [ -z $port ] || [ -z $user ]; then
    echo "$hostname is not in ~/.ssh/config at $ILLUMICONE_JUMPER, or Port and/or User are not specified for it."
    exit 1
fi

if [ "$pushpull" == "push" ]; then
    tofrom="to"
    deststr="\"$dest"\"
    cmd="scp -T -r -o \"ProxyJump $ILLUMICONE_JUMPER\" -P $port $sourcestr $user@127.0.0.1:\"'$dest'\""
else
    tofrom="from"
    cmd="scp -T -r -o \"ProxyJump $ILLUMICONE_JUMPER\" -P $port $user@127.0.0.1:\"$sourcestr\" \"$dest\""
fi
#echo "cmd=+${cmd}+"

echo "Copying $tofrom $hostname via tunneling port $port at $ILLUMICONE_JUMPER..."
eval $cmd
