#! /bin/bash
w1DeviceDir=`ls -1 /sys/bus/w1/devices/ | grep '28-'`
tempraw=$(cat /sys/bus/w1/devices/$w1DeviceDir/w1_slave | sed -n 's/.*t=\(-\?[0-9]\+\)/\1/p' | sed 's/-/_/')
tempc=$(dc -e "1 k $tempraw 1000 / n")
tempf=$(dc -e "1 k $tempraw 1000 / 9 * 5 / 32 + n")
now=$(date --iso-8601=s)
echo $now $tempraw $tempc $tempf
