#!/bin/bash
#~/devl/openpixelcontrol/bin/gl_server -l ~/devl/Illumicone/openpixelcontrol\ layouts/cone_med.json -p 7890 &
~/devl/Illumicone/sbin/startSimulatorGlServer
sleep 2
~/devl/Illumicone/src/patternController ~/devl/Illumicone/config/activeConfig.json >> ~/devl/Illumicone/patternController.out 2>&1 &
